markdown: kramdown
url: ''
title: 'DARK MATTER'
tagline: 'Beyond The Standard Model'
description: 'Beyond The Standard Model'
base_url: 'darkmatter.works'
twitter:
  username: darkmatter_work
  card: summary
logo: 'https://darkmatterworks.b-cdn.net/assets/images/logo_test.png'
social:
  name: Dark Matter
  links:
    - https://twitter.com/darkmatter_work
    - https://www.facebook.com/darkmatterllc
    - https://www.linkedin.com/company/77294788/
    - https://github.com/clarkedarkmatter
site-image: https://darkmatterworks.b-cdn.net/assets/images/dark.jpg
site-keywords: 'Digital'
favicon: https://darkmatterworks.b-cdn.net/assets/images/logo_test.png
heroimage: >-
  ''
email: bluejaystartup@gmail.com
phone: 614-600-4838
facebook_username: darkmatterllc
twitter_username: darkmatter_work
instagram_username: darkmatter.works
linkedin_username: 77294788
github_username: clarkedarkmatter
youtube_channel_id: UCjPVY-bdzK0RVmRL97ODBfw
reddit_username: darkmatter_works
behance_username:
dribbble_username:
spotify_username:
google-analytics: G-5Z8DJEKG3R
disqus-shortname: Dark Matter
author-name: Dark Matter
author-image: >-
  https://darkmatterworks.b-cdn.net/assets/images/logo_test.png
author-about: >-
  Marketing, for the Future.
author-about1: >-
  Dark matter is a hypothetical form of matter thought to account for approximately 85% of the matter in the universe - a fundamental element. Yet little is known about it's underlying properties.
author-about2: >-
  Quality * (Code + Content) == (Meaningful + Quantifiable) * Results
author-url: ''
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-minifier
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
